[game]
name = "Syphon Filter 2"
id = "SCUS-94451"
region = "USA"
exe = "input/SCUS_944.51"
disc = "input/Syphon Filter 2 (USA) (Disc 1).cue"
load_address = "0x80010000"
entry_pc = "0x800F8598"
text_size = "0x1DD000"
stack_base = "0x801FFFF0"

[recompiler]
seeds = "seeds/functions.txt"
bios_config = "psxrecomp-src/bios/OpenBIOS.toml"
strict = true
out_dir = "generated"

[runtime]
window_title = "Syphon Filter 2 Recompiled"
memcard_dir = "saves"
bios_hle = false
fast_boot = true
overlay_cache = true

[video]
renderer = "opengl"
supersampling = 4
antialiasing = true
texture_filtering = "nearest"
aspect_ratio = "16:9"
pgxp = true

[controller]
default_mode = "digital"
mouse_pad = true

[controller.mouse_camera]
enabled = true
facing_site = "0x80053464"
facing_expected = "0x8EA30034"
application_state_addr = "0x8011EE90"
player_pointer_addr = "0x8012A574"
player_state_offset = "0x20"
wrapper_offset = "0xE0"
base_offset = "0xA4"
owner_offset = "0xDC"
desired_pitch_offset = "0x8E8"
rendered_pitch_offset = "0x918"
vector_x_offset = "0xCC"
vector_y_offset = "0xD0"
vector_z_offset = "0xD4"
controller_reg = 18
chase_yaw_sensitivity = 0.75
chase_pitch_sensitivity = 1.0
aim_yaw_sensitivity = 1.0
aim_pitch_sensitivity = 1.0
invert_y = false

[widescreen]
native_wide = true
gte_game_mode = true
nw_phase_backdrop = false
nw_full_mirror = true
nw_guest_projection = true
nw_world_min_polygons = 64

[widescreen.cull]
auto_screen_x = true
screen_h_imms = ["0xE0", "0xF0", "0xF1"]
